name: jackieomykonos
favicon: null
layout_spectrum: 0.7799502750858665
typography_spectrum: 0.29916938696987927
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.13821555976755917
  lightness: 0.08274056226946414
  saturation: 0.7167982845567167
  rhythmicContrast: 0.8704124209471047
purpose: []
