name: "JackieO' Beach"
favicon: null
layout_spectrum: 0.79898
typography_spectrum: 0.47627
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#acc4d5'
    - '#8291a9'
    - '#fefaeb'
    - '#006e95'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
