name: "JackieO' Beach"
favicon: null
layout_spectrum: 0.24501
typography_spectrum: 0.10871
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#31211f'
    - '#ffffff'
    - '#e38e6c'
    - '#378afc'
    - '#ffd296'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
