favicon: null
name: "JackieO' Beach"
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.875
  brandStrength: 1
  lightness: 0.125
  brandColors:
    - '#06070c'
    - '#fffdf6'
    - '#af9055'
    - '#886a3d'
    - '#5d3023'
  rhythmicContrast: 0.5
typography_spectrum: 0.61087
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.24677
analytics:
  twitter: null
  google: null
  facebook: null
