name: "JackieO' Beach"
favicon: null
layout_spectrum: 0.9121863
typography_spectrum: 0.47627
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#31211f'
    - '#ffffff'
    - '#e38e6c'
    - '#378afc'
    - '#ffd296'
  brandStrength: 0.7879331
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
