favicon: null
name: "JackieO' Beach"
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9375
  brandStrength: 0.8357228
  lightness: 0
  brandColors:
    - '#31211f'
    - '#ffffff'
    - '#e38e6c'
    - '#378afc'
    - '#ffd296'
  rhythmicContrast: 0.25
typography_spectrum: 0.47627
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.46764
analytics:
  twitter: null
  google: null
  facebook: null
