name: "JackieO' Beach"
favicon: null
layout_spectrum: 0.60778
typography_spectrum: 0.52442
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "JACKIEO' BEACH"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#5b3d4a'
    - '#ffc992'
    - '#d47536'
  brandStrength: 0.875
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
