name: "JackieO' Beach"
favicon: null
layout_spectrum: 0.92836
typography_spectrum: 0.89301
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06070c'
    - '#fffdf6'
    - '#af9055'
    - '#886a3d'
    - '#5d3023'
  brandStrength: 0.9375
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
